states_capital = {
		'Abia':'Umuahia',
		'Adamawa':'Yola',
		'Akwa Ibom':'Uyo',
		'Anambra' : 'Awka',
		'Bauchi':'Bauchi',
		'Bayelsa':'Yenegoa',
		'Benue':'Makurdi',
		'Bornu':'Maiduguri',
		'Cross River':'Calabar',
		'Delta':'Asaba',
		'Ebonyi':'Abakaliki',
		'Edo':'Benin',
		'Enugu':'Enugu',
		'Ekiti':'Ado Ekiti',
		'Gombe':'Gombe',
		'Imo':'Owerri',
		'Jigawa':'Dutse',
		'Kaduna':'Kaduna',
		'Kano':'Kano',
		'Katsina':'Katsina',
		'Kogi':'Lokoja',
		'Kwara':'Ilorin',
		'Kebbi':'Benin Kebbi',
		'Lagos':'Ikeja',
		'Nassarawa':'Lafia',
		'Niger':'Mina',
		'Ogun':'Abeokuta',
		'Ondo':'Akure',
		'Osun':'Osogbo',
		'Oyo':'Ibadan',
		'Plateau':'Jos',
		'Rivers':'Port Harcourt',
		'Sokoto':'Sokoto',
		'Taraba':'Jalingo',
		'Yobe':'Damaturu',
		'Zamfara':'Gusau',
		}